apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-data-service
  namespace: proving-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-data-service
  template:
    metadata:
      labels:
        app: sensor-data-service
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: sensor
          image: sensor-data-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080