apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda-service
  template:
    metadata:
      labels:
        app: camunda-service
    spec:
      containers:
        - name: camunda
          image: camunda-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000  # Falls du z. B. logging/test-endpoints hast
          env:
            - name: SENSOR_SERVICE_HOST
              value: sensor-data-service
            - name: SENSOR_SERVICE_PORT
              value: "8080"
            - name: ZEEBE_ADDRESS
              value: camunda-zeebe-gateway:26500
---
apiVersion: v1
kind: Service
metadata:
  name: camunda-service
spec:
  selector:
    app: camunda-service
  ports:
    - port: 8000
      targetPort: 8000
